
# Resumen {-}

  La feminización de la sindicalización hoy es un fenómeno mundial. Distintas investigaciones han abordado el problema de la sindicalización femenina desde factores culturales que redundan en la pasividad de las mujeres y exclusión de estas en la acción colectiva. Ante la insuficiencia de un corpus que logre explicar por qué, en la actualidad,  hoy hay más mujeres en los sindicatos, la siguiente investigación pone énfasis en la importancia de las determinantes cíclicas, estructurales e institucionales de los cambios de la sindicalización. El aumento en la participación laboral femenina, la feminización de ciertas industrias, los cambios en las brechas salariales, aumento del empleo parcial y los distintos arreglos institucionales son algunos de las determinantes a considerar en un análisis de series temporales comparativo entre 45 países. Con la construcción de una [base de datos](../output/data) propia con cobertura de 1980-2018 cuyas principales fuentes de información son encuestas de hogares, datos administrativos, ICTWSS, ILO, Banco Mundial y OCDE, se estimaron modelos de corrección de error y usando efectos fijos se distinguió entre efectos a largo plazo y a corto plazo de las determinantes. 

**Palabras claves**: sindicalización, feminización, mercado laboral, salarios, tiempos de trabajo