# Agradecimientos {-}

A las compañeras de la Federación Nacional de Sindicatos de Trabajadoras de Casa Particular (FESINTRACAP), a María Cotal, Ruth Olate, Verónica Salas, Juana Collado y Silvia Poblete.

A las compañeras de la Unión Nacional de Manipuladoras de Alimentos (UNAMA) en especial a María Teresa Vejar. 

A las compañeras de la Federación de Call Center (FETRACALL), y especialmente a las del Sindikto, a Carola Guerra,   Larissa Matte, Nicole Cossio y Tamara Muñoz.

A otras sindicalistas que conocí en el camino, a las de NO+AFP, las de los supermercados, tiendas por departamento y bancos. También a las huelguistas que pude conocer encuestando para el Observatorio de Huelgas Laborales. 

A la primera trabajadora que conocí, mi mamá, y a una de las que más me ha inspirado, Vilma Correa. Sin ustedes, mi sueño de estudiar en la Universidad hubiese sido imposible. A mis amigas que me han enseñado de la rebeldía, Maríapaz Valle y Karina Cabrera. 

**Ustedes me enseñaron que otra sociedad es posible.** 

No puedo cerrar este proceso sin mencionar a las y los académicos que han estado presentes en mi proceso de formación. Mi profesor guía Omar Aguilar, quién me ha formado, me ha permitido ser su ayudante y nunca me hizo olvidar que “al final Valentina, todo esto que dices tiene que ver con la lucha de clases”. Del mismo modo, al profesor Giorgio Boccardo quién no solo me ha enseñado, sino que me permitió trabajar en su proyecto doctoral y aprender de los trabajadores del sector servicios. 

Al Dr. Pablo Pérez Ahumada co-tutor de esta tesis, quién me ha hecho recordar y utilizar el marxismo como ciencia, cada vez que me ha permitido investigar con él. Con ello, agradecer el espacio que del FONDECYT N°11190229 "Determinantes institucionales y políticos del conflicto entre empresarios y trabajadores: los casos de Argentina y Chile en perspectiva comparada", por darme un espacio desafiante de reflexión y perfeccionamiento. 

Gracias a la Dra. Catalina Arteaga, quién me abrió puertas para investigar con ella sobre las manipuladoras de alimentos y trabajadoras de la salud. Agradecer también a la Dra. Monica Gerber, Dr. Juan Carlos Castillo, Dr. Rodrigo Asún y profesor Cristóbal Moya. También, agradecer a mis compañeros José Antonio López y Julio Iturra. 

Por último, en el Grupo de Estudios Interdisciplinarios del Trabajo (GEIT) encontré no solo un lugar para desarrollarme, sino que grandes investigadores y amigos, llenos de rigurosidad y convicciones. A Felipe Ruiz,  Alejandro Castillo y Gabriel Sotomayor. Y a mi compañero de luchas y vida, Nicolás Ratto, quién me ha lanzado a no abandonar mis sueños y lograr ser una estudiosa del trabajo. 

**Espero que esta tesis esté a la altura de todo lo enseñado**



# Prólogo {-}

> *Las mujeres de la clase trabajadora necesitan a los sindicatos, y los sindicatos necesitan a las mujeres trabajadoras: hoy, la fuerza del sindicalismo es la mujer trabajadora*

Esta tesis es expresiva de un largo proceso de investigación y formación que se inició cuando, en mi primer año de Universidad, me aventuré a investigar el trabajo subcontratado de aseo. En ese proyecto descubrí que, pese a la debilidad estructural de este sector,  las trabajadoras organizadas lograron cambiar sus condiciones de vida y trabajo. Tiempo después, conocí con quienes comparto trabajo hasta hoy: las trabajadoras de casa particular. Desde el sindicato hasta la federación, esas mujeres me dieron la posibilidad no solo investigar cuestiones relativas al mercado laboral del trabajo doméstico asalariado, sino que me permitieron acompañarlas en su proceso de lucha, realizando campañas, planeando proyectos, disfrutando triunfos y sufriendo derrotas. En el camino fui conociendo la organización colectiva de distintas trabajadoras. Entre ellas, pude indagar el empleo de call center, donde me encontré con mujeres sindicalistas que me enseñaron cómo un proceso de trabajo con tanto control taylorista puede ser resistido y con éxito por las trabajadoras. A contracorriente de la precariedad, estas mujeres se organizaban igual.

Si bien hasta ese entonces el movimiento de los trabajadores era uno de mis temas de mayor interés, el fenómeno de la sindicalización de trabajadoras me comenzó a inquietar mucho más. Un hecho decisivo fue un hito que recuerdo fielmente, sobre todo cómo una brújula que me permitió no abandonar esta investigación pese a las críticas sobre la importancia de este: en la marcha del 1° de Mayo centenares de mujeres trabajadoras abriendo paso por las grandes alamedas, una protesta y conmemoración marcada por la asistencia de las trabajadoras de la salud, manipuladoras de alimentos, educadoras de párvulos y funcionarias del servicio público. Llegamos al final de la marcha y sobre el escenario entonaba su discurso la presidenta de la Central Unitaria de Trabajadores. Esa escena, una marcha rodeada por trabajadoras y encabezada por una mujer, despertaron mi inquietud sociológica. No mentiré, no era la marcha más grande, la erosión del clásico movimiento sindical era palpable, pero una luz de revitalización y un nuevo actor, una nueva sujeta de la clase trabajadora pensé que era plausible. 

Genuinamente me puse a buscar datos que explicaran qué estaba ocurriendo, encontrando que para el último año en Chile, [la sindicalización femenina había superado a la masculina](https://fabricadedatoslaborales.cl/las-mujeres-y-el-trabajo-asalariado-claves-sobre-su-participaci%C3%B3n-sindical/). Apenas se presentó la oportunidad, volví a terreno a estudiar a quiénes habían captado mi atención por su masividad y energía, las manipuladoras de alimentos. En contacto con ellas, la idea de que esta nueva sujeta, la trabajadora de los servicios, precaria e inestable, se lograba organizar gracias a la sororidad de clase ha calado hondo en mis reflexiones.  En lugares de trabajo feminizados se daba la particularidad de que las mujeres de clase trabajadora se entendían y acompañaban ante sus precarias condiciones laborales. 

Y ahí estaban organizándose y muchas veces protestando. Y con más dudas y certezas, la acción de estas trabajadoras me ha llevado a querer construir evidencia científica y un programa de investigación que ponga en el centro la feminización del conflicto laboral.  A ellas les debo esas inquietudes y los resultados de esta investigación, que espero que contribuya en ponerlas en el centro como actoras relevantes en el conflicto capital-trabajo. 

