# Metodología {#method}


## Data y variables

Los datos usados en esta investigación provienen de la construcción de una base de datos longitudinal (FDL[^1]) sobre relaciones laborales a partir de la unión de fuentes como ICTWSS, OCDE, ILO y Banco Mundial, que proveen información temporal a nivel de los países. A esto se agrega la estimación y validación de los dos indicadores principales para este estudio, que son la densidad sindical femenina y masculina, que fueron construidas a partir de encuestas de hogares, encuestas a fuerza de trabajo y/o datos administrativos para los países en estudio (ver [Apéndice A](#apendicea)). FDL es una base de datos longitudinal que contiene 3360 observaciones y 340 variables laborales, económicas e instituciones a partir de información desde 1960 a 2018 de 56 países del mundo. Como se puede evidenciar en la Tabla [3.1](#tab3-1), gran parte de estos países corresponden a países OCDE, y aquellos que no son países OCDE pertenecen al G20.

Tabla 3.1: Países seleccionados según continente

```{r tab3-1, echo=FALSE, warning= F, message= F}
db1 <- db %>% dplyr::select("País"="country", "Continente"="continent") %>% dplyr::distinct(País, Continente)
DT::datatable(db1, options = list(
  language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json'),
  pageLength = 5
))
```

</br>

El periodo de análisis abarca entre los años 1980 y 2018, por las mismas razones teóricas y empíricas indicadas por Vachon et. al (2016). Primero, no existe disponibilidad de datos para todas las variables rezagadas antes de 1980 – solo 10 países tienen datos desde 1960. Segundo, desde 1980 se reconoce el inicio del periodo neoliberal del desarrollo capitalista [@baccaro2011;@tomaskovic-devey2015] lo que permite evidenciar los inicios del proceso de crecimiento del sector servicio, desregulación del mercado laboral y divergencia del papel del Estado en las relaciones laborales. Tercero, es importante notar que el intervalo de tiempo permite considerar el efecto de la crisis económica de 2008 en la densidad sindical. 

### Variable dependiente

*$FUD_{i}$*

La variable dependiente en esta tesis es la feminización de la densidad sindical (Feminization Union Density Index-FUDi), que es un índice que mide la división sexual de la densidad sindical mediante la relación de las densidades sindicales por sexo en una única dimensión, es decir, la afiliación sindical neta de mujeres y hombres como proporción de los asalariados en el empleo. Esta variable fue estimada y validada en base a dos indicadores principales para este estudio, que son la densidad sindical femenina y masculina, que fueron construidas a partir de encuestas de hogares, encuestas a fuerza de trabajo y/o datos administrativos para los 56 países en estudio (para más detalles de fuentes y consistencia ver [Apéndice A](#apendicea)).

$$FUD_{i} = \frac{\frac{NUM_{f}*100}{WSEE_{f}}}{{\frac{NUM_{m}*100}{WSEE_{m}}}} = \frac {UD_{f}}{UD_{m}}$$
Donde,

- $NUM$: Número de afiliados en organizacioones sindicales
- $WSEE$: Número de asalariados del total de la fuerza de trabajo
- $UD$: Densidad sindical 
- El subíndice $f$ indica femenino y $m$ masculino

Los valores de $FUDi$ oscilan entre 0,26 a 2,12, mediana 0,9516 y desviación estándar 0,3416. Cuando FUDi es cercano a 1, indica que la densidad sindical femenina y masculina son iguales. Mientras que cuando $FUDi$ es sobre 1 expresa que la densidad sindical femenina es mayor a la masculina. En ese caso se habla de una densidad sindical femenizada. 

### Variables independientes

*Determinantes Cíclicas*

Para capturar los efectos del ciclo económico sobre la densidad sindical se probará la relación con el desempleo y los salarios reales, que son obtenidos por la base LFS (Labor Force Statistics) recopiladas por la OIT y OCDE respectivamente.

El *desempleo femenino* se mide como el porcentaje anual de desocupadas del total de la fuerza de trabajo femenina, dejando afuera a ocupadas e inactivas del cálculo. Los *salarios mínimos* reales se miden por hora y anualmente, deflactadas por los índices nacionales de precios al consumidor. Los datos de salarios mínimos se convierten en una unidad monetaria común que utiliza las Paridades de Poder Adquisitivo (PPA) en dólares, con el objeto de medir el poder de compra efectivo de los salarios. 

**Determinantes Estructurales**

El *empleo en el sector servicios* se define como la tasa anual de la fuerza de trabajo en el sector servicios, es decir, en las actividades de las secciones económicas que van de la G a la U en la Clasificación Industrial Estándar Internacional [cf. Naciones Unidas  -@nacionesunidas2008; ver [Apéndice A](#apendicea) ].  El tamaño de las actividades productivas proviene de la estimación de OIT y son recopiladas por el Banco Mundial. 

La *participación laboral femenina* es calculada como la fuerza de trabajo femenina dividida por el total de mujeres en edad de trabajar, la cual depende de los países, pero en general esta va desde los 15 a los 64 años. 

La *incidencia del empleo parcial* corresponde al porcentaje de trabajadores parciales en el total de los asalariados de cada país. Esta es una medida que varía según la definición del empleo parcial para cada país,  pero en general se define por jornadas que van entre 30 a 35 horas por semanas. Tanto la participación laboral femenina como la incidencia del empleo parcial provienen de LFS que es recopilada por OCDE. 

### Variables de interacción

*Determinantes Institucionales*

Para poder distinguir entre economías coordinadas y liberales, se utilizará la variable coordinación salarial construida por @visser2019 en ICTWSS. En términos teóricos, la variable se define como grado de coordinación institucional que hay sobre el mercado laboral [@kenworthy2001;@kenworthy2003], donde 1 indica una negociación localizada en las firmas y 5 indica una negociación centralizada y vinculante. En consecuencia, la coordinación salarial es una forma de medir la centralización y coordinación de las políticas laborales, y evidencia reciente demuestra un patrón claro de alta coordinación salarial en CMEs y baja en LMEs [@baccaro2011; @hassel2015; @kim2015]. En términos prácticos, coordinación salarial fue escogida pues dentro de las medidas de centralización, es de las variables que tiene mayor disponibilidad de datos para un mayor número de países.

### Variables de control

Se controlará por variables que han sido tradicionalmente utilizadas en los estudios de sindicalización. Primero, las variables de control sindicales son la densidad sindical previa como una forma de controlar el efecto anterior de la variable dependiente sobre sí misma y la cobertura de la negociación colectiva, porque como se ha indicado la densidad sindical de algunos países muestran una alta correlación con esta variable – a excepción de Francia. Segundo, si bien la literatura tradicional considera variables del ciclo económico control, como en esta investigación son variables sustantivas, solo se controlará por crecimiento económico. 


## Modelo

Esta investigación utiliza un análisis de series de tiempo y transversal para 56 países durante 1980 a 2018, o 2128 países-años. Se analizan los efectos que tienen los determinantes cíclicos, estructurales e institucionales en la feminización de la densidad sindical con un modelo de corrección de error (ECM). La razón principal tiene que ver con que estos modelos capturan los efectos a corto y a largo plazo de las variables, pudiendo distinguir entre ellas las variables “cíclicas” y las “estructurales”, respectivamente [@checchi2005; @disney1990]. A su vez, ECMs permiten modelar efectos con variables no estacionarias y cointegradas [@beck2011] , esto es establecer relaciones lineales con variables que tienen tendencias (de ascenso o descenso) a largo plazo pero integrando también las de ciclo o coyuntura [@checchi2005]

La literatura especializada sobre densidad sindical ha planteado que el ECM permite responder a las explicaciones de cambio[cf. @carruth1988; @disney1990], pero también de diferencias entre países [@schnabel2002], principalmente porque permite identificar una serie de especificaciones [^2]  de variables para distintas explicaciones teóricas [@keele2016]

En términos procedimentales para corregir la heteroscedasticidad producida por que la varianza de los errores difiere por cada uno de los países, se emplean errores estándares  especificados como panel [cf. @beck1995] y una corrección autorregresiva de primer orden [@vachon2016], esto es un modelo aleatorio en donde se estima la media de la variable dependiente ($FUDi$) según la media de sus observaciones pasadas.

A su vez, se han incluido en los modelos una serie de efectos fijos para mostrar la invariabilidad de algunas variables por países (e.g institucionales, que por lo general son estables), lo que permite que las diferencias entre países de deban más a la baja varianza dentro del país, que a diferencias no observadas entre países – por casos perdidos. Para aquellas variables que tienen una mayor variación se ha realizado imputaciones múltiples, es decir, se han rellenado los casos perdidos a partir de procesos estocásticos – considerando estructuras de pérdidas de dato de tipo MCAR [@young2015]. 

En relación a las ecuaciones estimadas,  se parte desde un modelo de punto muerto  [cf. dead start model en @keele2016],  que permite establecer un punto de referencia en el tiempo,. Esto desde el supuesto de que a largo plazo existe un equilibrio pero que es posible distinguir tendencias a corto plazo y a largo plazo. La ecuación de punto muerto se específica en la Formula \@ref(eq:central) [^2], donde


\begin{equation} 
  \triangle FUDi_{i,t} = \alpha_1,i + t- \beta_1FUDi_{i,t-1}+ \beta_2X_{i,t-1}+ \epsilon_{i,t}
  (\#eq:central)
\end{equation} 

Donde,

- $\triangle FUDi_{t}$ representa la primera diferencia entre $FUDi_{t}$ y $FUDi_{t-1}$

- $i$ representa cada uno de los países

- $\alpha_1,i$ representa la desviación en el tiempo para cada país

- $\beta_1$ representa la tasa de ajuse o correción de errores de $FUDi$

- $\beta_2$: efecto directo de la variable $X_{i,t-1}$ sobre $\triangle FUDi$

- $X_{i,t-1}$: determinate de la densidad sindical

El modelo se lee como: un aumento unitario de $FUDi_{t-1}$ conduce a una disminución unitaria de $\beta_1$ en $\triangle FUDi_{t}$ y, por lo tanto, seproduce un aumento unitario de $\beta_1$ en $FUDi_{t}$, controlando por el resto de las variables. En consecuencia, el efecto acumulado a largo plazo de un aumento unitarario de $X_{i}$ en $FUDi$ es la suma de una serie geométrica infinita, donde $n$ representa el numero de unidades tiempo-países que tienen efectos directos sobre la feminización de la densidad sindical. 


\begin{equation} 
  \sum_{n=0}^{\infty} \beta_2(1-\beta_1)^{n} = 1
  (\#eq:sum)
\end{equation} 

Reemplazando la ecuación \@ref(eq:central) con la sumatoria \@ref(eq:sum), la ecuación final que contiene la predicción de la variación de $FUDi$ ($\triangle FUDi$) a largo plazo se basa en el modelo de @engle1987 para densidad sindical:


\begin{equation} 
  FUDi_{i,t} = \beta_1^{-1}\alpha_1,i + t- \beta_1^{-1}(1-\beta_1)\triangle FUDi_{i,t}+ \beta_1^{-1}\beta_2X_{i,t-1}+ \epsilon_{i,t}
  (\#eq:final)
\end{equation} 

Finalmente, con el objetivo de probar la hipótesis de interacción entre participación laboral femenina y crecimiento del sector servicios de @haile2017 pero ahora nivel nacional, se estimará un modelo final que incluye dicha interacción entre aquellas variables.  

[^1]:Fábrica de Datos Laborales o FDL es una base de datos de construcción reproducible. Por ello la construcción, validación y procesamiento de FDL responde a los criterios @tier2020 y está libre en el repositorio de esta tesis. A su vez, la base de datos se actualiza cada vez que las fuentes principales de información actualizan la información que suben a sus sitios web. A su vez se puede encontrar en el siguiente link el libro de códigos donde se especifica la medición de cada una de las variables. 

[^2]: Esto se refiere a que no existe una clarificación de la cadena causal-temporal de las variables. Los modelos han determinado que el salario determina a la densidad sindical, pero no se considera como la inflación pueden mediar esa relación dentro del ciclo económico, y, en consecuencia, se pasa por alto las teorías de la inflación del empuje salarial. También, no es claro si los modelos empíricos es el nivel o tasa de desempleo la que juega el rol de inhibir el crecimiento sindical. Otro problema se deriva de la especificación de los salarios debido a que, si los precios y salarios aumentan al mismo ritmo, los salarios reales no cambiarían, entonces el “efecto crediticio” y “efecto amenaza” deberían modelados a partir de los salarios reales o controlando por la inflación. En consecuencia, si los beneficios sindicales son un bien normal, solo un aumento de los salarios reales debería aumentar la demanda por sindicalización. 

[^3]: Esta ecuación proviene del equilibrio entre la ecuación de las variables a corto plazo y la ecuación de las variables a largo plazo. Para más ver [Apéndice A](#apendicea)
