# Conclusión {#conclusion}

Si 1980 fue nombrada la década de la emergencia de la deregulación, la tercerización y feminización del mercado laboral  (Standing, 1989), nuestros resultados nos permiten decir que, producto de estos cambios, en los 2000 se inaugura la época de la tercerización y feminización sindical. El tipo de empleo, las relaciones laborales y la precariedad asociada a "los empleos de mujeres" que se han promovido desde aquella época, resultaron no solo en un aumento de la participación laboral femenina y un declive en el empleo masculino, sino que también, en un cambio en el conflicto laboral que se ve reflejado ahora en *quién* es esa nueva trabajadora que se organizaba sindicalmente.

Esta noción se sigue de lo planteado por @visser2012 cuando señala que los cambios en el mercado laboral no son neutrales en el conflicto laboral, y más bien no solo influencian el nivel de sindicalización, sino que también afectan quienes se unen a las organizaciones sindicales y quienes no (p.100). Este efecto selectivo muestra evidencia sustantiva a partir de las determinantes estructurales, que permiten afirmar que a nivel mundial tanto la feminización de la participación laboral como la feminización del sector servicios muestran un efecto positivo y significativo sobre la feminización sindical. La lógica indica que, si las mujeres crecen en número lo suficientemente para hablar de que están concentradas en la fuerza de trabajo (i.e, que se feminice), la estructura sindical tradicional se va a poner en tensión produciendo la salida de los hombres y el ingreso de las mujeres. De hecho, cuando se comentó los modelos de los efectos específicos por país, notamos evidencia internacional que podía apoyar esta idea, al menos nacionalmente: en Nueva Zelanda e Inglaterra se habló de las *Women Structures (WS)* [@parker2010; @haile2017], en Japón y Corea se les nombró *women-only* [@broadbent2005; @broadbent2007]. En consecuencia, en primer término, esta idea de la feminización y tercerización de los conflictos laborales, que inicialmente se delineó en Alemania [@artus2015], al menos para los 45 países en estudio, muestra evidencia satisfactoria. 

No se puede hablar con el mismo entusiasmo con el cuál fueron tratados, por  la literatura internacional, el resto de los determinantes que se señalaron como relevantes para los cambios en la densidad sindical. Por un lado, el efecto procíclico de variables como los salarios mínimos reales, productividad laboral o masculinización del desempleo, no muestran efectos contundentes sobre la feminización sindical. Como se indicó, los modelos regionales nos aportan lo sensible que podrían ser variables como estas ante la presencia de sistemas de seguridad social, siendo significativas en la mayoría de los países que carecen de seguridad al desempleo y pensión. Ahora bien, no se debe olvidar que, siguiendo los desarrollos empíricos en la temática, estos factores fueron estudiados a corto plazo y, en consecuencia, investigaciones futuras podrían probar qué incidencia tienen estos a largo plazo. 

Por otro lado, contrario el fuerte apoyo que han recibido desde la literatura los factores institucionales, al menos la centralización de la coordinación muestra un pequeño efecto. Ante ese escenario se modelaron los efectos específicos de los países, de modo de abordar un análisis discriminante de los coeficientes y visualizando al menos descriptivamente si los países más “liberales” y “coordinados” muestran efectos similares sobre $FUDi$. Los resultados nos muestran señales de que los países liberales (eg. Chile, Nueva Zelanda, Inglaterra) presentan patrones comunes claros, no así los coordinados. Ello sugiere que se debe avanzar de manera más rigurosa en la especificación de estas determinantes.   

En consecuencia, podemos probar la tesis general de este estudio, esto es, que debido a que las mujeres son la nueva fuerza laboral y, dada su concentración, estas se han transformado en la nueva fuerza sindical, se ha feminizado la organización sindical. Ahora bien, esta tesis de las *pink collars* puede ser reforzada a partir de un trabajo más arduo en la especificación de las actividades comprometidas en el sector servicios. Si bien por cuestiones de comparabilidad y disponibilidad de datos a nivel mundial se hizo uso de la categoría general de sector servicios, dada las diferencias en condiciones de trabajo, futuras investigaciones deben abordar cómo el sector de servicios sociales (salud y educación), financieros y de comercio pueden producir efectos diferenciados sobre la feminización sindical. Hipótesis como estas permiten explicar de manera más precisa como cambios macro (feminización sindical) podrían ser micro-fundados por factores económicos-laborales como las condiciones de trabajo. 
Otros aspectos de especificación de los modelos que nos permiten avanzar en este programa de investigación se puntualizarán enseguida. En primer lugar, dado los resultados de los factores cíclicos, es importante avanzar en un control estadístico que considere el tipo de provisión de seguridad social por país. Debido a la ausencia de estadísticas temporales y nacionales que permitan hacer análisis como estos, esfuerzos en esta línea implicarán realizar aportes de sistematización de la base de datos construida. En segundo lugar, dado los resultados insatisfactorios para los salarios mínimos reales y la coordinación salarial, la especificación más rigurosa de las variables salariales, esto es, siguiendo la línea de que estas deben ser tratadas en su genderización, implicarían probar el efecto que podría tener la brecha salarial sobre la feminización sindical. Si bien esta variable fue inicialmente pensada para esta investigación, la disponibilidad de este dato solo cubre desde los años 2000, solo de países OCDE y sin un tratamiento ponderado, algo que hace difícil su comparabilidad. 

Si se observa el panorama general de esta investigación una de las principales lecciones es que, contrario a los estudios de género que han puesto a las mujeres como estructuralmente limitadas en su acción sindical, esta investigación muestra dos contrapuntos a estos enfoques: primero,  la feminización sindical a nivel mundial es un hecho que ya se ha concretado en varios países del mundo y, en aquellos que no, ocurrirá a largo plazo; y segundo, esta variación es explicada por determinantes económicas-laborales, es decir, para entender la feminización sindical hay que poner la mirada en cómo los procesos de producción afectan de manera diferenciada a las mujeres.

En ningún caso esto implica que factores culturales no tengan incidencia en la feminización sindical. Pero, como se propuso al inicio, el ímpetu de esta pesquisa era no solo mostrar qué explicaba la feminización sindical, sino que probar que los factores económicos tenían mucho qué decir sobre esto. Sin embargo, la misma pesquisa demostró lo complejo que es el fenómeno de la feminización de la sindicalización, esto en parte, por el efecto de “grupo” que tiene la composición sexual de las estructuras sindicales. Si bien @haile2017 abordó esto para Inglaterra, investigaciones futuras podrían extender este análisis para más países y aplicando técnicas como los modelos multinivel longitudinal se podría estimar si son estos factores a nivel empresa que explican el cambio o más bien son a nivel país.

Ahora bien, sea la feminización a nivel empresa o a nivel nacional, el conflicto laboral es un fenómeno complejo. Un aspecto no reflexionado en esta investigación dice relación en cómo no solo se aborda la organización de las trabajadoras en sindicatos, sino que también avanzando en cómo las mujeres participan en huelgas laborales. Autoras como @milkman2013 y @artus2015 muestran estudios de casos sobre esto, pero ante la evidencia del carácter global del fenómeno sindical, un análisis temporal y comparado de las huelgas laborales puede aportar en este horizonte. Por último, y no menor, estos estudios más amplios y ambiciosos serán necesarios a la luz de la crisis económica y social que se avecina producto de la pandemia por COVID-19, que como ha mostrado ya la evidencia internacional, ha tenido un serio efecto en la precarización de condiciones de vida y trabajo de las mujeres ¿Entraremos en una fase de mayor conflicto?
